name: syosetu_reader
description: "Ứng dụng đọc truyện từ Syosetu."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  url_launcher: ^6.2.4
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.4
  beautiful_soup_dart: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
